export default {
  base: {
    base: 'base',
    enumList: '/enum/list',
    enumAdd: '/enum/add',
    enumEdit: '/enum/edit',
    enumDelete: '/enum/delete',
    enumDetail: '/enum/detail',
    enumFormat: '/enum/format',

    setupList: '/setup/list',
    setupAll: '/setup/all',
    setupAdd: '/setup/add',
    setupEdit: '/setup/edit',
    setupDelete: '/setup/delete',
    setupDetail: '/setup/detail',

    smsList: '/sms/list',
    smsDelete: '/sms/delete',
    smsTemplateList: '/sms/template/list',
    smsTemplateAdd: '/sms/template/add',
    smsTemplateEdit: '/sms/template/edit',
    smsTemplateDelete: '/sms/template/delete',
    smsTemplateDetail: '/sms/template/detail',
    smsSend: '/sms/send',

    areaList: '/area/list',
    areaAll: '/area/all',
    areaAdd: '/area/add',
    areaEdit: '/area/edit',
    areaDelete: '/area/delete',
    areaDetail: '/area/detail',
    advertList: '/advert/list'
  },
  user: {
    base: 'user',
    userLogin: '/user/login',
    userRegister: '/user/register',
    userRetrieve: '/user/retrieve',
    userQuery: '/user/query',
    userLogout: '/user/logout',
    userUpdate: '/user/update',

    userList: '/user/list',
    userAdd: '/user/add',
    userEdit: '/user/edit',
    userDetail: '/user/detail',
    userDelete: '/user/delete'
  },
  file: {
    base: 'file',
    fileAll: '/file/all',
    fileList: '/file/list',
    fileDelete: '/file/delete',
    fileUpload: '/file/upload',
    fileMerge: '/file/merge',
    fileCheck: '/file/check',
    backetAll: '/backet/all',
    backetList: '/backet/list',
    backetAdd: '/backet/add',
    backetEdit: '/backet/edit',
    backetDetail: '/backet/detail',
    backetDelete: '/backet/delete'
  },
  nft: {
    base: 'nft',
    activityList: '/activity/list',
    activityAll: '/activity/all',
    activityAdd: '/activity/add',
    activityEdit: '/activity/edit',
    activityDelete: '/activity/delete',
    activityDetail: '/activity/detail',
    activityJoin: '/activity/join',
    activityAwards: '/activity/awards',

    blindboxList: '/blindbox/list',
    blindboxAll: '/blindbox/all',
    blindboxAdd: '/blindbox/add',
    blindboxEdit: '/blindbox/edit',
    blindboxDelete: '/blindbox/delete',
    blindboxDetail: '/blindbox/detail',
    blindboxAwards: '/blindbox/awards',
    blindboxCollect: '/blindbox/collect',
    blindboxOpen: '/blindbox/open',

    communityList: '/community/list',
    communityAll: '/community/all',
    communityAdd: '/community/add',
    communityEdit: '/community/edit',
    communityDelete: '/community/delete',
    communityDetail: '/community/detail',
    communityJoin: '/community/join',

    labelList: '/label/list',
    labelAll: '/label/all',
    labelAdd: '/label/add',
    labelEdit: '/label/edit',
    labelDelete: '/label/delete',
    labelDetail: '/label/detail',

    nftList: '/nft/list',
    nftAll: '/nft/all',
    nftAdd: '/nft/add',
    nftEdit: '/nft/edit',
    nftDelete: '/nft/delete',
    nftDetail: '/nft/detail',
    nftCollect: '/nft/collect',
    nftCollectList: '/nft/collect/list',
    nftCollectDetail: '/nft/collect/detail',
    nftCollectEdit: '/nft/collect/edit',
    nftCollectGive: '/nft/collect/give',
    nftCollectMall: '/nft/collect/mall',

    orderList: '/order/list',
    orderAll: '/order/all',
    orderCreate: '/order/create',
    orderDetail: '/order/detail',
    orderCheck: '/order/check',

    accountQuery: '/account/query',
    accountStat: '/account/stat',
    accountFlow: '/account/flow',
    accountWithdraw: '/account/withdraw',
    bankcardBind: '/bankcard/bind',
    bankcardUnbind: '/bankcard/unbind',
    bankcardQuery: '/bankcard/query'
  }
}
